### ISSUE TITLE
Similar tool

### ISSUE THREAD

**Issue by inian** [avodonosov/pocl#1]
Not an issue per se..But have you checked this (http://research.microsoft.com/en-us/projects/doloto/)?
Quite similar in approach. 

Btw, are you planning to release the code for this project?

**Comment by avodonosov** [comment]
Hi, thanks for the link, similar indeed. From their description, it's not clear, do they limit the solution by javascript, or they somehow fix HTML too (they just say "code").

People have shown me another similar tool: https://www.instartlogic.com/blog/dont-buy-the-javascript-you-dont-use

As for releasing the code, it's likely I will release it although I am not decided 100% yet; and publishing the code isn't a priority now anyway.

I want to turn it into a production-ready solution, and to study the approach further. It would be nice to find funding for several month of work, and I consider partnering with some CDN or web acceleration company. It doesn't necessary rule out public release of the code, but other variants are possible too (keep the code private, dual license).

I see many great open projects which suffer from lack of resources. If someone spends efforts which are not compensated, he runs out of power very quickly and the project stalls. I think there are cases when commercial approach can be more benefitial, for everyone (and users in the first place).

But on the other hand, if I don't find a sponsor/partner, I will most likely continue work on the project, in free time.

**Comment by avodonosov** [comment]
Added the links to both products to the README
